import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { FaMoon } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <nav className="fixed top-0 w-full flex justify-between items-center py-4 px-16">
          <Link href={"/"} className="text-xl font-semibold tracking-wide">BolaBits</Link>
          <div className="flex gap-8">
            <Link href={"/components"}>Components</Link>
            <Link href={"/installation"}>Installation</Link>
            <Link href={"/blogs"}>Blogs</Link>
          </div>
          {/* to create light and dark mode */}
          <div>
            <div className="rounded-full border p-2">
              <FaMoon />
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
